config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'topics#index'

  resources :topics, only: [:index, :new, :create, :show] do
    resources :messages, except: [:show]
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :topic_categories
  has_many :topics, through: :topic_categories
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :messages
  has_many :topic_categories
  has_many :categories, through: :topic_categories

  def self.search(search)
    if search
      Topic.joins(:messages).where(['title LIKE ? OR text LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Topic.all
    end
  end

end

app/models/topic_category.rb
class TopicCategory < ApplicationRecord
  belongs_to :topic
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name ,presence: true
         has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_topic, only: [:create]

  def create
    @message = Message.new(message_params)
    @message.save!
    redirect_to "/topics/#{@topic.id}"
  end


  private
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id, topic_id: @topic.id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:edit, :show]

  def index
    @topics = Topic.all.order("created_at DESC")
  end

  def new
    @topic = Topic.new
    @categories = Category.all
  end

  def create
    @topic = Topic.new(topic_params)
    category_ids = params[:topic][:category_ids]
    @message = params[:topic][:message]

    if category_ids.present? and @message.present?
      @topic.save!
      
      category_ids.each do |category_id|
        @topic_category = TopicCategory.new(category_id: category_id, topic_id: @topic.id)
      end
      first_message_create

    else
      redirect_to action: :new
    end

  end


  def first_message_create
    @first_message = Message.new(text: @message, user_id: current_user.id, topic_id: @topic.id)
    @first_message.save!
  end


  def show
    @messages = Message.where(topic_id: @topic.id)
    @message = Message.new
  end


  def search
    @topic_searchs = Topic.search(params[:search_word]).order("created_at DESC").uniq
  end


  private
  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, category_ids: [])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BulletinBoard
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/topics/_header.html.haml
.header
  .header__logo
    = link_to "Bulletin Board", root_path
  .header__right
    - if user_signed_in?
      .header__right--loggingIn
        .loggingName
          こんにちは
          = current_user.name
          様
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'loggingIn'
    - else
      .header__right--regist
        = link_to "新規登録", '/users/sign_up', class: 'regist'
      .header__right--login
        = link_to "ログイン", '/users/sign_in', class: 'login'

app/views/topics/create.html.haml
= render 'header'
%br
%br
スレッドの作成が完了しました。

app/views/topics/index.html.haml
.top-page
  = render 'header'

  - if user_signed_in?
    = link_to "スレッド作成", new_topic_path

  %br
  %br

  .top-page__search__keyword__title
    ■キーワードで検索
  .top-page__search__keyword__form
    = form_with(url: search_topics_path, local: true, method: :get, class: "search-form") do |f|
      = f.text_field :search_word, autocomplete: "content", placeholder: "キーワードを入力してください" ,class: 'search-input'
      = f.submit "検索" ,class: 'submit-button'

  %br

  - if @topics.present?
    .topics-list
      %ul
        - @topics.each do |topic|
          %li.topics-list__content
            .topics-list__content__title
              = link_to "スレッドタイトル：#{topic.title}", "/topics/#{topic.id}", method: :get
            .topics-list__content__category
              カテゴリ：
              - topic.topic_categories.each do |topic_category|
                = topic_category.category.name
                |
          %br
  - else
    ※まだスレッドは作成されていません。

app/views/topics/new.html.haml
= render 'header'
%br
%br

スレッド作成ページ
%br
%br

.topic-new-page__form
  = form_with(model: @topic, url: topics_path, local: true, method: :post) do |f|
    = render "devise/shared/error_messages", resource: @topic

    .topic-new-page__form__title
      .topic-new-page__form__title__title
        スレッドタイトル
    .topic-new-page__form__title-form
      = f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "スレッドのタイトルを入力してください" ,class: 'title-form'
    %br

    .topic-new-page__form__category
      .topic-new-page__form__category__title
        スレッドカテゴリ(複数選択可)
    .topic-new-page__form__category-form
      = f.collection_check_boxes :category_ids, @categories, :id, :name, include_hidden: false do |b|
        = b.label { b.check_box + b.text }
    %br

    .topic-new-page__form__message
      .topic-new-page__form__message__title
        スレッドタイトル
    .topic-new-page__form__message-form
      = f.text_area :message, autofocus: true, autocomplete: "text", placeholder: "最初のレスメッセージを入力してください" ,class: ''
    %br

    .topic-new-page__form__actions
      = f.submit "スレッドを作成する" ,class: 'submit-button'

app/views/topics/search.html.haml
= render 'header'

.search-page
  %ul
    - @topic_searchs.each do |topic|
      %li.search-page__topics-list

        .search-page__topics-list__title
          = link_to "スレッドタイトル：#{topic.title}", "/topics/#{topic.id}", method: :get
        .search-page__topics-list__category
          カテゴリ：
          - topic.topic_categories.each do |topic_category|
            = topic_category.category.name
            |
          %br

app/views/topics/show.html.haml
= render 'header'

%br

= "スレッドタイトル：#{@topic.title}"

.messages-list
  %ul
    - @messages.each do |message|
      %li.messages-list__content
        = message.user.name
        %br
        = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
        %br
        = safe_join(message.text.split("\n"),tag(:br))
        %br

%br

- if user_signed_in?
  .message-form
    .message-form__title
      投稿入力フォーム
    .message-form__form
      = form_with(model: @message, url: "/topics/#{@topic.id}/messages", local: true, method: :post) do |f|
        = render "devise/shared/error_messages", resource: @message

        = f.text_area :text, autofocus: true, autocomplete: "text", placeholder: "メッセージを入力してください" ,class: ''

        .message-form__form__actions
          = f.submit "投稿する", class: 'submit-button'